# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5c787f4990e96a0d9c14680abc36bb6f90a4627631ee8d33a994fd8a2f2b9a429c390578f9be552766cd9ed1a87a4b4618120fa330355cca718dad843e9ab51

test:
  secret_key_base: c3205005350368e0f1e112a9e041b1fab9564d1e02f00bbc6c21e216a2d9ae9e75d7d2bc3bdb9a3e5f9521a03b965fdaafbce54abfdac81161e9536c91a43d2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
